"""Generates the module panels (res/*.svg) with all text as paths.

Rack's SVG renderer ignores <text>, so every label is converted to outlines here, from
the DejaVu Sans font that ships with Rack. Each panel is written in a light and a dark
version (Rack picks one by the user's "prefer dark panels" setting).

Positions are in millimetres and must match the component layout in
src/IndexedQuadSeq.cpp and src/SequencerController.cpp.

    py scripts/make_panels.py [path/to/DejaVuSans.ttf]
"""

import os
import sys

from fontTools.pens.svgPathPen import SVGPathPen
from fontTools.pens.transformPen import TransformPen
from fontTools.ttLib import TTFont

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DEFAULT_FONT = r"C:\Program Files\VCV\Rack2Pro\res\fonts\DejaVuSans.ttf"

THEMES = {
    "light": {"background": "#d8dadc", "ink": "#2b2d30", "slot": "#2b2d30", "slotInner": "#0d0e10"},
    "dark": {"background": "#24262a", "ink": "#c4c7cb", "slot": "#0d0e10", "slotInner": "#000000"},
}
LINE_WIDTH = 0.3


class Font:
    """Lays text out the way nanovg/fontstash does, so the panels match what was drawn
    at runtime: the scale is size / (ascent - descent), and middle alignment puts the
    baseline (ascender + descender) / 2 * size below the given y."""

    def __init__(self, path):
        self.font = TTFont(path)
        self.glyphs = self.font.getGlyphSet()
        self.cmap = self.font.getBestCmap()
        hhea = self.font["hhea"]
        self.height = hhea.ascent - hhea.descent
        self.ascender = hhea.ascent / self.height
        self.descender = hhea.descent / self.height

    def width(self, text, size):
        scale = size / self.height
        return sum(self.glyphs[self.cmap[ord(c)]].width for c in text) * scale

    def path(self, text, x, y, size, align):
        scale = size / self.height
        width = self.width(text, size)
        if align == "center":
            x -= width / 2
        elif align == "right":
            x -= width
        baseline = y + (self.ascender + self.descender) / 2 * size
        d = []
        for c in text:
            glyph = self.glyphs[self.cmap[ord(c)]]
            pen = SVGPathPen(self.glyphs, ntos=lambda v: ("%.3f" % v).rstrip("0").rstrip("."))
            glyph.draw(TransformPen(pen, (scale, 0, 0, -scale, x, baseline)))
            if pen.getCommands():
                d.append(pen.getCommands())
            x += glyph.width * scale
        return " ".join(d)


class Panel:
    def __init__(self, width_hp):
        self.width = width_hp * 5.08
        self.height = 128.5
        self.items = []  # (kind, data)

    def label(self, x, y, text, size=2.5, align="center"):
        self.items.append(("label", (x, y, text, size, align)))

    def line(self, *points):
        self.items.append(("line", points))

    def raw(self, svg):
        """Shapes given as SVG, with {ink}/{slot}/... filled in per theme."""
        self.items.append(("raw", svg))

    def write(self, path, theme, font):
        colors = THEMES[theme]
        out = [
            '<?xml version="1.0" encoding="UTF-8"?>',
            "<!-- Generated by scripts/make_panels.py; edit that instead. -->",
            '<svg xmlns="http://www.w3.org/2000/svg" width="%.2fmm" height="%.1fmm" viewBox="0 0 %.2f %.1f">'
            % (self.width, self.height, self.width, self.height),
            '  <rect x="0" y="0" width="%.2f" height="%.1f" fill="%s"/>' % (self.width, self.height, colors["background"]),
        ]
        strokes, texts = [], []
        for kind, data in self.items:
            if kind == "line":
                pts = " ".join("%.2f,%.2f" % p for p in data)
                strokes.append('    <polyline points="%s"/>' % pts)
            elif kind == "label":
                x, y, text, size, align = data
                texts.append('    <path d="%s"/>' % font.path(text, x, y, size, align))
            else:
                out.append("  " + data.format(**colors))
        out.append('  <g fill="none" stroke="%s" stroke-width="%.2f" stroke-linecap="round" stroke-linejoin="round">'
                   % (colors["ink"], LINE_WIDTH))
        out += strokes
        out.append("  </g>")
        out.append('  <g fill="%s">' % colors["ink"])
        out += texts
        out.append("  </g>")
        out.append("</svg>")
        with open(path, "w", encoding="utf-8", newline="\n") as f:
            f.write("\n".join(out) + "\n")


# --- Indexed Quad Sequencer (26HP) ------------------------------------------------------

def sequencer():
    p = Panel(26)
    ROW_TOP = 17.0
    ROWS = [33.0, 48.9, 64.9, 80.8]
    JACK_ROW_1, JACK_ROW_2 = 97.8, 113.4
    L_DISPLAY_X, L_BUTTON_X = 49.1, 66.6
    R_BUTTON_X, R_DISPLAY_X = 80.5, 97.9
    VOLTAGE_DISPLAY_X = 105.0
    DISPLAY_W, VOLTAGE_DISPLAY_W = 14.2, 28.2
    FN_COL_1, FN_COL_2 = 12.4, 27.6
    LOOP_LED_X, LOOP_BUTTON_X = 111.1, 119.4
    TRACK_JACK_X = [[39.4, 52.3, 65.5], [78.8, 91.8, 105.0]]
    big, small, tiny = 2.6, 2.0, 1.7
    label_dy, btn_top = 6.2, 4.0

    # Section frames.
    p.raw('<g fill="none" stroke="{ink}" stroke-width="0.3">'
          '<rect x="2.8" y="7.9" width="126.5" height="111.6" rx="2.5"/>'
          '<line x1="2.8" y1="22.9" x2="129.3" y2="22.9"/>'
          '<path d="M2.8,71.8 H71.8 A2.5,2.5 0 0 1 74.3,74.3 V87.0"/>'
          '<line x1="2.8" y1="87.0" x2="129.3" y2="87.0"/></g>')

    p.label(66.04, 4.3, "INDEXED QUAD SEQUENCER", 3.2)
    p.label(66.04, 124.2, "JIN NG", 2.2)

    # TABLE switch and SMOOTH.
    p.label(14.0, 10.3, "TABLE", small)
    p.label(10.4, ROW_TOP - 3.2, "A", tiny, "right")
    p.label(10.4, ROW_TOP, "ref", tiny, "right")
    p.label(10.4, ROW_TOP + 3.2, "B", tiny, "right")
    p.label(37.2, ROW_TOP - 3.4, "smooth", tiny)
    p.line((23.4, 11.6), (24.6, 11.6), (24.6, 10.0), (25.8, 10.0))  # step ...
    p.line((26.4, 10.8), (27.6, 10.8))                              # ... becomes ...
    p.line((27.2, 10.4), (27.6, 10.8), (27.2, 11.2))
    p.line((28.2, 11.6), (29.4, 11.6), (30.8, 10.0), (31.8, 10.0))  # ... a ramp

    # Display captions, each with a bracket down to its focus button.
    def left_caption(row, text):
        y = row - label_dy
        x0 = L_DISPLAY_X - DISPLAY_W / 2
        p.label(x0, y, text, big, "left")
        p.line((x0 + font.width(text, big) + 1.0, y), (L_BUTTON_X, y), (L_BUTTON_X, row - btn_top))

    def right_caption(row, text, display_x, display_w):
        y = row - label_dy
        x1 = display_x + display_w / 2
        p.label(x1, y, text, big, "right")
        p.line((x1 - font.width(text, big) - 1.0, y), (R_BUTTON_X, y), (R_BUTTON_X, row - btn_top))

    left_caption(ROW_TOP, "INDEX")
    right_caption(ROW_TOP, "VOLTAGE", VOLTAGE_DISPLAY_X, VOLTAGE_DISPLAY_W)
    p.label(122.6, ROW_TOP + 0.4, "V", 5.0, "left")
    for row, left, right in zip(ROWS, ["TRACK", "PATTERN", "STEP", "SNAPSHOT"], ["CV-A", "CV-B", "DURATION", "GATE"]):
        left_caption(row, left)
        right_caption(row, right, R_DISPLAY_X, DISPLAY_W)

    # Function buttons.
    for x, row, text in [(FN_COL_1, 0, "INSERT"), (FN_COL_1, 1, "DELETE"), (FN_COL_1, 2, "MATH"),
                         (FN_COL_2, 2, "COPY"), (FN_COL_1, 3, "LOAD"), (FN_COL_2, 3, "SAVE")]:
        p.label(x, ROWS[row] - label_dy, text, big)
    p.label(36.2, ROWS[2] - 3.2, "press", tiny)
    p.label(36.2, ROWS[2] + 3.4, "INSERT", tiny)

    # LOOP bracket, START/END and the loop-back arrow between their LEDs.
    loop_y, loop_x = ROWS[2] - 11.4, 117.4
    p.label(loop_x, loop_y, "LOOP", big)
    p.line((LOOP_LED_X - 2.0, loop_y + 1.6), (LOOP_LED_X - 2.0, loop_y), (loop_x - 5.0, loop_y))
    p.line((loop_x + 5.0, loop_y), (126.6, loop_y), (126.6, loop_y + 1.6))
    p.label(LOOP_BUTTON_X, ROWS[2] - 5.6, "START", small)
    p.label(LOOP_BUTTON_X, ROWS[3] - 5.6, "END", small)
    p.line((LOOP_LED_X - 1.3, ROWS[2] - 4.0), (LOOP_LED_X + 1.3, ROWS[2] - 4.0))
    p.line((LOOP_LED_X, ROWS[2] - 4.0), (LOOP_LED_X, ROWS[3] + 4.0))
    p.line((LOOP_LED_X - 1.3, ROWS[3] + 4.0), (LOOP_LED_X + 1.3, ROWS[3] + 4.0))
    mid = (ROWS[2] + ROWS[3]) / 2
    p.line((LOOP_LED_X - 0.8, mid - 0.8), (LOOP_LED_X, mid + 0.4), (LOOP_LED_X + 0.8, mid - 0.8))

    # Jacks.
    p.label(FN_COL_1, 92.4, "PAUSE", tiny)
    p.label(26.0, 91.2, "CLOCK", big)
    p.label(26.0, 106.8, "RESET", big)
    p.line((FN_COL_1 + 4.0, JACK_ROW_1), (26.0 - 4.2, JACK_ROW_1))
    p.line((FN_COL_1 + 4.0, JACK_ROW_2), (26.0 - 4.2, JACK_ROW_2))
    for t in range(4):
        y = JACK_ROW_1 if t < 2 else JACK_ROW_2
        xs = TRACK_JACK_X[t % 2]
        y_title = y - 8.9
        p.label(xs[1], y_title, "TRACK %d" % (t + 1), small)
        p.line((xs[0] - 3.0, y_title + 1.2), (xs[0] - 3.0, y_title), (xs[1] - 6.0, y_title))
        p.line((xs[1] + 6.0, y_title), (xs[2] + 3.0, y_title), (xs[2] + 3.0, y_title + 1.2))
        for x, text in zip(xs, ["CV-A", "CV-B", "GATE"]):
            p.label(x, y - 6.4, text, tiny)
    p.label(LOOP_BUTTON_X, 92.4, "COMMIT", tiny)
    p.label(LOOP_BUTTON_X, 106.8, "MODE", big)
    p.label(119.6, 110.8, "hold", tiny, "left")
    p.label(119.6, 114.0, "edit", tiny, "left")
    p.label(119.6, 117.2, "follow", tiny, "left")
    return p


# --- Sequencer Controller (14HP) ----------------------------------------------------------

def controller():
    p = Panel(14)
    DISPLAY_X, DISPLAY_W = 18.8, 14.2
    BUTTON_X, COL_1 = 35.8, 8.5
    JACK_1, JACK_2 = 49.4, 63.1
    ROW_TOP, ROW_PART, ROW_GROUP, ROW_MODIFIER = 17.4, 33.2, 48.9, 80.5
    MOD_ROWS = [48.9, 64.8, 80.5]
    REC_ROW_1, REC_ROW_2 = 96.8, 112.7
    big, small, tiny = 2.6, 2.0, 1.7

    p.raw('<g fill="none" stroke="{ink}" stroke-width="0.3">'
          '<rect x="2.8" y="7.9" width="65.5" height="111.6" rx="2.5"/>'
          '<path d="M43.0,7.9 V21.0 A2.5,2.5 0 0 0 45.5,23.5 H68.3"/>'
          '<line x1="2.8" y1="40.1" x2="68.3" y2="40.1"/>'
          '<line x1="2.8" y1="86.7" x2="68.3" y2="86.7"/>'
          '<rect x="16.2" y="56.7" width="25.7" height="14.1" rx="2.5"/></g>')
    # The STORAGE card slot.
    p.raw('<rect x="60.2" y="9.8" width="2.0" height="13.0" rx="0.4" fill="{slot}"/>')
    p.raw('<rect x="60.7" y="10.4" width="1.0" height="11.8" rx="0.2" fill="{slotInner}"/>')

    p.label(35.56, 4.3, "SEQUENCER CONTROLLER", 3.2)
    p.label(35.56, 124.2, "JIN NG", 2.2)

    # Parts and storage.
    p.label(COL_1, 11.9, "RESET TO", small)
    p.line((COL_1 + 4.0, ROW_TOP), (16.2 - 1.4, ROW_TOP))
    p.label(29.0, 11.9, "TRANSITION", small)
    p.line((29.0 + font.width("TRANSITION", small) / 2 + 0.8, 11.9), (BUTTON_X, 11.9), (BUTTON_X, ROW_TOP - 4.0))
    for y, text in [(14.9, "user"), (17.4, "first"), (19.9, "last")]:
        p.label(25.4, y, text, tiny, "left")
    p.label(45.0, 11.9, "STORAGE", small, "left")
    for y, text in [(14.9, "user"), (17.4, "admin"), (19.9, "eject")]:
        p.label(50.6, y, text, tiny, "left")
    p.label(65.6, 11.4, "I/O", tiny)
    p.label(65.6, 17.6, "error", tiny)
    x0 = DISPLAY_X - DISPLAY_W / 2
    p.label(x0, 27.4, "PART", big, "left")
    p.line((x0 + font.width("PART", big) + 1.0, 27.4), (BUTTON_X, 27.4), (BUTTON_X, ROW_PART - 4.0))
    p.label(JACK_1, 27.4, "SELECT", small)
    p.label(JACK_2, 27.4, "ACTIVATE", small)

    # Groups.
    p.label(x0, 43.2, "GROUP", big, "left")
    p.line((x0 + font.width("GROUP", big) + 1.0, 43.2), (BUTTON_X, 43.2), (BUTTON_X, ROW_GROUP - 4.0))
    p.line((7.3, ROW_GROUP + 1.5), (7.3, 57.6))
    p.label(COL_1, 59.1, "(DE)SELECT", small)
    p.label(22.2, 59.1, "INVERT", small)
    p.label(BUTTON_X, 59.1, "ROTATE", small)
    p.label(3.9, 74.8, "GROUP MODIFIERS", big, "left")
    p.line((3.9 + font.width("GROUP MODIFIERS", big) + 1.0, 74.8), (BUTTON_X, 74.8), (BUTTON_X, ROW_MODIFIER - 4.0))
    for y, a, b in [(78.1, "high", "X"), (80.5, "slope", "Y"), (82.9, "low", "Z")]:
        p.label(11.2, y, a, tiny, "left")
        p.label(22.2, y, b, tiny, "left")
    for y, channel in zip(MOD_ROWS, "XYZ"):
        p.label(JACK_1, y - 5.7, "CV", small)
        p.label(JACK_2, y - 5.7, "GATE", small)
        p.label(56.3, y - 2.6, "mod", tiny)
        p.label(56.3, y + 0.3, channel, 2.4)
        p.line((54.8, y - 1.1), (57.8, y - 1.1), (57.8, y + 1.7), (54.8, y + 1.7), (54.8, y - 1.1))

    # Recording.
    p.label(COL_1, 92.1, "ARM", small)
    for x, top, bottom in [(22.2, "A-1", "(cv-a)"), (BUTTON_X, "A-2", "(cv-b)"), (JACK_1, "AD-1", "(gate)")]:
        p.label(x, 88.8, top, small)
        p.label(x, 91.2, bottom, small)
    p.label(JACK_2, 88.5, "PUNCH", small)
    p.label(JACK_2, 90.9, "IN/OUT", small)
    p.label(COL_1, 103.4, "RECORD", small)
    p.label(COL_1, 105.7, "MODE", small)
    for y, text in [(110.1, "alter"), (112.6, "step"), (115.1, "real-time")]:
        p.label(11.2, y, text, tiny, "left")
    for x, top, bottom in [(22.2, "D-1", "(insert)"), (BUTTON_X, "D-2", "(delete)"), (JACK_1, "AD-2", "(duration)")]:
        p.label(x, 104.5, top, small)
        p.label(x, 107.0, bottom, small)
    p.label(59.0, 104.7, "REC", small, "right")
    p.line((JACK_2, REC_ROW_1 + 4.2), (JACK_2, 103.2))
    p.line((JACK_2, 106.2), (JACK_2, REC_ROW_2 - 4.0))
    return p


if __name__ == "__main__":
    font = Font(sys.argv[1] if len(sys.argv) > 1 else DEFAULT_FONT)
    for name, build in [("IndexedQuadSeq", sequencer), ("SequencerController", controller)]:
        panel = build()
        for theme in THEMES:
            suffix = "" if theme == "light" else "-dark"
            out = os.path.join(ROOT, "res", name + suffix + ".svg")
            panel.write(out, theme, font)
            print("wrote", os.path.relpath(out, ROOT))
